### ISSUE TITLE
Maybe seperate Dota and Steam in different "scripts"

### ISSUE THREAD

**Issue by Jaglag** [ClaudeBot/hubot-steam-webapi#3]
Hi Mrsaints
Maybe seperate both scripts to get a better overview i think dota should be standalone to get more features.
It´s a bit confusing to have Steam and dota commands in 1 script.

**Comment by MrSaints** [comment]
I somewhat agree, but they both use the same API though.

**Comment by Jaglag** [comment]
it doesnt matter in my op if they both use the same APi but they use both different commands.
1 is mainly for Dota and the other one is for Steam itself to lookup users.

**Comment by MrSaints** [comment]
There are only 4 commands at the moment, and they are all related to the package name. Until it starts to grow, I don't think it needs to be separated yet.

**Comment by Jaglag** [comment]
ok
